### ISSUE TITLE
Wrong coronal, sagittal image size

### ISSUE THREAD

**Issue by gatechke** [pollackscience/pyviz_med#1]
When the number of slices in the Z direction is smaller (e.g., 125 slices in Z direction vs. 512 slices in X, Y direction), the image size is also smaller in the coronal and sagittal planes.  
![image](https://user-images.githubusercontent.com/8482358/84539723-f2c6c580-acc1-11ea-8612-4232f7d95872.png)

**Comment by pollackscience** [comment]
Now should be fixed, image sizes are computed based on the input size, the resolution, and the spacing.
